### PR TITLE
Fixed `view` method issue + `nft_contract_metadata` update issue

### PR DESCRIPTION
**Pull request by AshenI99**
Fixed `init` function not updating `nft_contract_metadata`.
Fixed `view` methods are recognising as `call` methods.

### CODE REVIEW

**Comment by AshenI99** [comment]
Hi @devey, @achrafismyname,

Our structure was clean and correct. I saw similar structures in several `nft` codebases here.
[https://github.com/learn-near?q=L1](https://github.com/learn-near?q=L1)

But we were getting an error while calling `view` methods. I went through old commits and checked where we started to messed up. So the messed up code piece is the below one. 

https://github.com/curaOS/contracts/blob/34a492b45c836a376914ae3c084832af33e7b7c5/as/cNFT/assembly/models/persistent_nft_contract_metadata.ts#L65-L66
<br/>So our structure is perfectly fine and working without any issues. What's happening is `PersistentNFTContractMetadata` class constructor is always writing to the storage every time when we use contract.

https://github.com/curaOS/contracts/blob/34a492b45c836a376914ae3c084832af33e7b7c5/as/cNFT/assembly/models/persistent_nft_contract_metadata.ts#L42-L56
<br/>In other models, we are not writing to the `storage` in their `constructor's`. So we don't need to change everything like in here #62. So this fix or similar to this one would work.  :-)

**Comment by achrafismyname** [comment]
Oh yes, you are right about this, it's only `persistent_nft_contract_metadata` writing to the storage and causing this. This is much easier to fix then :)

**Review by achrafismyname — APPROVED** [review]

**Comment by AshenI99** [comment]
> 

Great news :-)

**Comment by AshenI99** [comment]
> Oh yes, you are right about this, it's only `persistent_nft_contract_metadata` writing to the storage and causing this. This is much easier to fix then :)
> 
> * I tested this in testnet and all issues related to this are fixed :)
> * The sandbox test is working as expected

Great news :-)

**Pull request merged**
